from . import contrato_padre
from . import contrato_hijo
from . import vehicle
from . import gps_brand
from . import gps_model
#from . import mp_fleet_service_type
#from . import mp_fleet_vehicle
#from . import mp_fleet_vehicle_assignation_log
#from . import mp_fleet_vehicle_log_services
#from . import mp_fleet_vehicle_model
#from . import mp_fleet_vehicle_model_brand
#from . import mp_fleet_vehicle_model_category
#from . import mp_fleet_vehicle_odometer
#from . import mp_fleet_vehicle_state
#from . import mp_fleet_vehicle_tag
#from . import mp_res_config_settings
#from . import mp_res_partner